/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: b1866fadbcc26c9ae0019b759a191cd0)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	DATABASE_URL: string;
	NEXT_PUBLIC_APP_NETWORK: string;
	NEXT_PUBLIC_RPC_MAINNET: string;
	NEXT_PUBLIC_RPC_TESTNET: string;
	NEXT_PUBLIC_PENGU_MAINNET: string;
	NEXT_PUBLIC_PENGU_TESTNET: string;
	NEXT_PUBLIC_TREASURY_ADDRESS: string;
	GECKOTERMINAL_NETWORK: string;
	GECKOTERMINAL_POOL: string;
	SUBSCRIPTION_1D_PRICE_PENGU: string;
	SUBSCRIPTION_7D_PRICE_PENGU: string;
	SUBSCRIPTION_30D_PRICE_PENGU: string;
	SUBSCRIPTION_365D_PRICE_PENGU: string;
	SUBSCRIPTION_LIFETIME_PRICE_PENGU: string;
	SESSION_SECRET: string;
	WORKER_SELF_REFERENCE: Fetcher /* pengusignal */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "NEXT_PUBLIC_APP_NETWORK" | "NEXT_PUBLIC_RPC_MAINNET" | "NEXT_PUBLIC_RPC_TESTNET" | "NEXT_PUBLIC_PENGU_MAINNET" | "NEXT_PUBLIC_PENGU_TESTNET" | "NEXT_PUBLIC_TREASURY_ADDRESS" | "GECKOTERMINAL_NETWORK" | "GECKOTERMINAL_POOL" | "SUBSCRIPTION_1D_PRICE_PENGU" | "SUBSCRIPTION_7D_PRICE_PENGU" | "SUBSCRIPTION_30D_PRICE_PENGU" | "SUBSCRIPTION_365D_PRICE_PENGU" | "SUBSCRIPTION_LIFETIME_PRICE_PENGU" | "SESSION_SECRET">> {}
}
